<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="repo.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="repo.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CloseGroup\CloseGroup.csproj" />
  </ItemGroup>

</Project>
